### ISSUE TITLE
Gradle build not working

### ISSUE THREAD

**Issue by CodingMeSwiftly** [cats-oss/android-gpuimage#141]
Error:Artifact 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.2.1-SNAPSHOT:gpuimage-library.jar' not found.

This is the error I get after adding this to my build.gradle file
repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.2.1-SNAPSHOT'
}

How can I resolve this issue?

**Comment by eosrei** [comment]
This is works as documented. Issue can be closed.
