### ISSUE TITLE
aidl is missing!

### ISSUE THREAD

**Issue by lyuku** [cats-oss/android-gpuimage#143]
Hi, I download this project, and try to build it in android studio, and I got the error message: Execution failed for task ':library:CompileDebugAidl'. Aidl is missing.
I don't know what' wrong and cannot find any helpful message on google. So can you help me?

**Comment by WalterDaniel** [comment]
Hi men, can you share how do you solve the problem??
Thanks

**Comment by wuhen0929** [comment]
This was several months ago, and I can't remember the details. It's kind of Android SDK thing, I didn't get it configure right. Sorry, couldn't help you more.
