### ISSUE TITLE
GPUImageView's background color at CENTER_INSIDE scale type

### ISSUE THREAD

**Issue by euler0** [cats-oss/android-gpuimage#147]
It always looks black and the view's android:background attribute is not working to me.

Is there any way to change the background color?

![screenshot_2014-12-13-08-47-25](https://cloud.githubusercontent.com/assets/549734/5421385/5733157e-82a6-11e4-891c-3217c046c0cb.png)

**Comment by dockusan** [comment]
Are you using gpuImageView.setBackground?
If yes, just using gpuImageView.setImage, and android:background attribute can using.

**Comment by srajesh529** [comment]
Hi euler0 is solve your issue?if solve,please tell how to solve the issue.
Thanks

**Comment by toptuto** [comment]
sorry but i cant change it , when i use android:background then all the gpuImageView turns to the color i set in background

**Comment by monxarat** [comment]
You can using `gpuImageView.setBackgroundColor(red, blue, green);` , But this method not supported alpha value.

If you want to set the color with alpha, you must override method `GPUImageRenderer`, `GPUImage`, and `GPUImageView`.

override `GPUImageRenderer` class

```
class MyGPUImageRenderer extends GPUImageRenderer{

private float alpha;

@Override
    public void onSurfaceCreated(final GL10 unused, final EGLConfig config) {
        super.onSurfaceCreated(unused, config);
        ...
        GLES20.glClearColor(backgroundRed, backgroundGreen, backgroundBlue, alpha);
        ...
    }
    
    public void setAlpha(float alpha) {
        this.alpha = alpha;
    }
}
```

override `GPUImage` class

```
class MyGPUImage extend GPUImage {
    
    /**
     * Sets the background color
     *
     * @param red   red color value
     * @param green green color value
     * @param blue  red color value
     */
    public void setBackgroundColor(float red, float green, float blue, float alpha) {
        renderer.setAlpha(alpha);
        renderer.setBackgroundColor(red, green, blue);
    }
}
```

Extends `GPUImageView` to holding all method from it.
```
class MyGPUImageView extend GPUImageView {
     
     private MyGPUImage gpuImage;
     
     /**
     * Sets the background color
     *
     * @param red   red color value
     * @param green green color value
     * @param blue  red color value
     */
    public void setBackgroundColor(float red, float green, float blue, float alph) {
        gpuImage.setBackgroundColor(red, green, blue, alph);
    }
}
```

**Comment by euler0** [comment]
It‘s been such a long time!

As of December 2019, @tnylee and @monxarat's answers are maybe the best way to solve this problem.

Thank you all!
