### ISSUE TITLE
Only 2 Scale Types.?

### ISSUE THREAD

**Issue by deepinder10** [cats-oss/android-gpuimage#251]
I needed to use Matrix Scale Type, but there are only 2 types center_crop and center_inside.

**Comment by UseLived** [comment]
@deepinder10 do you fixed this? i have the same problem,please help me.

**Comment by feresr** [comment]
+1 on this, are the plans to support this?

**Comment by feresr** [comment]
Alright, I created a PR for this, hope it gets merged soon 🤞 

https://github.com/cats-oss/android-gpuimage/pull/469
