### ISSUE TITLE
Filter preview inside RecyclerView makes lagging ?

### ISSUE THREAD

**Issue by bbincybbaby** [cats-oss/android-gpuimage#341]
` GPUImage gpuImage = new GPUImage(mContext);
                 gpuImage.setImage(background);
                 gpuImage.setFilter(GPUImageFilterTools.createFilterForType(mContext, effect.getType()));
                 gpuImage.requestRender();
                 Bitmap bitmap=gpuImage.getBitmapWithFilterApplied();
                 holder.imageView.setImageBitmap(bitmap);
                 gpuImage.deleteImage();`

RecyclerView filter preview creating lag on my phone ?

**Comment by nguyenquocchinhdev** [comment]
You can apply effect to image by using Picasso

`Picasso.with(mContext).load(imageUri).resize(iconPreviewWidth, iconPreviewHeight).into(new Target() {
  @Override
  public void onBitmapLoaded(final Bitmap bitmap, Picasso.LoadedFrom from) {
gpuImage.setFilter(GPUImageFilterTools.createFilterForType(mContext, effect.getType()));
  imageView.setImageBitmap(gpuImage.getBitmapWithFilterApplied(bitmap));
  }

  @Override
  public void onBitmapFailed(Drawable errorDrawable) {

  }

  @Override
  public void onPrepareLoad(Drawable placeHolderDrawable) {

  }
  });`

**Comment by androidapkr** [comment]
OOM Error while using this method, can you please guide how to handle Memory
