### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by deepakrokz** [cats-oss/android-gpuimage#380]
Hi @wasabeef 
can you please help me out of this error
Error:Gradle DSL method not found: 'getObjects()'

I am getting this error using gradle 2.3.0, I am stuck at this, please reply ASAP. 
I will be very thankful to you.

**Comment by wasabeef** [comment]
We're re-working for 2.0.0, so please wait a few weeks.
https://github.com/cats-oss/android-gpuimage/pull/403
