### ISSUE TITLE
It doesn`t work everything. continuously error error error...

### ISSUE THREAD

**Issue by supenir** [cats-oss/android-gpuimage#401]
sample project doesn`t work.
new project importing library also doesn`t work.

'Could not get unknown property 'GROUP' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.'
what is this?

**Comment by wasabeef** [comment]
We're re-working for 2.0.0, so please wait a few weeks.
https://github.com/cats-oss/android-gpuimage/pull/403
