### ISSUE TITLE
problem occurred when preview,so many zabra crossing on my phone screen

### ISSUE THREAD

**Issue by jw20082009** [cats-oss/android-gpuimage#429]
# Bug Reporting
problem occurred when preview,so many zabra crossing on my phone screen
![qq 20181105212411](https://user-images.githubusercontent.com/8803478/48000748-7103d300-e141-11e8-8d1b-fa37f7c10ed8.png)

**Comment by wasabeef** [comment]
Could you tell me your device info?

**Comment by jw20082009** [comment]
I tried 3 devices, and met the same problem. MI 8 or Oppo R9s or Smartisan OS103

**Comment by itome** [comment]
I created PR about this issue -> https://github.com/cats-oss/android-gpuimage/pull/430
@jw20082009 Could you try my patch in your devices?

**Comment by jw20082009** [comment]
I will try later

**Comment by itome** [comment]
@jw20082009 Did you try? Please let me know.

**Comment by jw20082009** [comment]
I get into trouble while building project, the android studio says "Gradle sync failed: Unsupported method:NativeArtifact.getSourceFolders()."
![af95c2aa-30f8-48b7-af5b-e326010c8bd5](https://user-images.githubusercontent.com/8803478/48350443-2db9df00-e6c2-11e8-8f12-0ee29e70ea9a.png)

**Comment by wasabeef** [comment]
@jw20082009 
Hi sir,
Could you update to newer android studio and ndk?

**Comment by jw20082009** [comment]
@wasabeef 
Issue was done,but preview size seems so small,and suggest a stable version of com.android.tools.build:gradle may be more robust.
<img width="272" alt="qq20181112-220319 2x" src="https://user-images.githubusercontent.com/8803478/48352272-4bd60e00-e6c7-11e8-9518-d19121504e42.png">
