### ISSUE TITLE
setBackgroundColor not work

### ISSUE THREAD

**Issue by onexuan** [cats-oss/android-gpuimage#466]
I use setBackgroundColor(204,204,204), but it does not work (#cccccc)

**Comment by wasabeef** [comment]
I tried the following code.

`gpuImageView.setBackgroundColor(255f, 255f,0f)`

<img src="https://user-images.githubusercontent.com/1833474/62928513-a259af80-bdf3-11e9-9ed1-e107ce55fbcb.png" width="50%" />

**Comment by onexuan** [comment]
but setBackgroundColor(204,204,204) not work

**Comment by onexuan** [comment]
Fix
`
int uColor = 0xFFF7F7F7;
//float fAlpha = (float)(uColor >> 24) / 0xFF;
float fRed = (float)((uColor >> 16) & 0xFF) / 0xFF;
float fGreen = (float)((uColor >> 8) & 0xFF) / 0xFF;
float fBlue = (float)(uColor & 0xFF) / 0xFF;
gpuImage.setBackgroundColor(fRed, fGreen, fBlue);
`
