### ISSUE TITLE
How to add mask overlay on image ?

### ISSUE THREAD

**Issue by chihung93** [cats-oss/android-gpuimage#475]
My design is combining contrast, brightness,vibrance and `mask overlay`.
How to add mask overlay on the image?

![My MaskOverlay ](https://i.imgur.com/812j8Yg.png)

`Expected Result `

![Expected Result ](https://i.imgur.com/OUQkoPw.png)

**Comment by monxarat** [comment]
You can use a Filter Blend

**Comment by chihung93** [comment]
Thanks @monxarat , Done
