### ISSUE TITLE
How to use a blending effect?

### ISSUE THREAD

**Issue by mohsinnaqvi110** [cats-oss/android-gpuimage#477]
# Usage Of Blend Filters

There are multiple blend modes available but the usage is unclear.

for example: If I try to put Overlay blend effect on two images, Is this a correct way to do that as I am confuse How do I add the second image to get a proper output; Even In the shader it takes to texture inputs;

    Uri imageUri = ...;
    gpuImageView = findViewById(R.id.gpuimageview);
    gpuImageView.setImage(imageUri); // this loads image on the current thread, should be run in a thread
    gpuImageView.setFilter(new GPUImageOverlayBlendFilter());

Anybody; Correct way?

**Comment by IAmWilling** [comment]
Now I have a project that needs to use multiple filters to stack each output result together, but it will have a serious picture picture conflict effect. I hope the author can solve this big problem!
