### ISSUE TITLE
getBitmapWithFilterApplied() returns width -1

### ISSUE THREAD

**Issue by irfano** [cats-oss/android-gpuimage#70]
If I use

GPUImage mGPUImage = new GPUImage(EditActivity.this);
mGPUImage.setFilter(new GPUImageSepiaFilter());
Bitmap bm = mGPUImage.getBitmapWithFilterApplied(bitmap);
imageView.setImageBitmap(bm);

in onCreate there is no problem. But when using it in my seekbar's OnSeekBarChangeListener, getBitmapWithFilterApplied(bitmap) returns width -1. I can't find the problem. Anyone experience this problem?

**Comment by gang018** [comment]
what was the solution to your problem? 
I have the same issue

**Comment by jeetdholakia** [comment]
same here , any solutions?

**Comment by irfano** [comment]
I can't remember the solution. But it may because of "bitmap" parameter of "getBitmapWithFilterApplied(bitmap)". Did you create that bitmap with sizes before calling getBitmapWithFilterApplied(bitmap)?
