### ISSUE TITLE
Could not find an filter effect for the GPUImageTiltShiftFilter

### ISSUE THREAD

**Issue by chunfun** [cats-oss/android-gpuimage#79]
I want to find a tilt shift  filter effect for android,but I can not see a filter call GPUImageTiltShiftFilter for android which looks like GPUImageTiltShiftFilter for iphone.I try to write it but have the black color.Can you help me? Thanks!

**Comment by qq297110281** [comment]
@chunfun  did you success?

**Comment by asozcan** [comment]
You can achieve this with renderscript and combine with GPUImage, they works together. I inspired from RSImage library, you can take a look.

**Comment by qq297110281** [comment]
use the GPUImageFilterGroup and GPUImageTwoInputFIlter custom a filter Group, finally can it work. thx!!
